# SPDX-License-Identifier: GPL-3.0-or-later

build/daemon/%/entry: $(lib-obj-y) $(daemon-obj-y) \
		      build/libusb.a \
		      build/libdeflate.a
	mkdir -p $(@D)
	$(CC) $(LDFLAGS) \
	      $(filter %.o,$^) \
	      $(filter %.a,$^) \
	      $(DAEMON_LDFLAGS) \
	      -o $@

build/libusb.a: libusb/libusb-1.0.a
	mkdir -p $(@D)
	ln -f $< $@

build/libdeflate.a: libdeflate/build/libdeflate.a
	mkdir -p $(@D)
	ln -f $< $@

libusb/libusb-1.0.a libdeflate/build/libdeflate.a:
	$(error No $@ found. \
		Run 'scripts/build-$(firstword $(subst /, ,$@)).sh' first)

build/daemon/cmdtree:

build/daemon/.commands:
